
--Setup
USE IAACE1;
GO

/*
Creates a schema
Moves tables from an existing schema into the new schema
*/

--Creating a new schema TRNPAY
CREATE SCHEMA TRNPAY;

/*
Notes
need to find a way to move all tables w/o specifying them individually
*/

--Moving the tables from old schema to new schema
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_EARN_CODE_DETAIL;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_EMPL_INFO;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_JOB_INFO_DETAIL;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_PAYCHECK_TAX_2013;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_PAYCHECK_TAX_2014;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_PAYCHECK_TAX_2015;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_PAYCHECK_TAX_2016;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_PAYCHECK_TAX_TRANSLATE;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_W2_2013;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_W2_2014;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_W2_2015;
ALTER SCHEMA TRNPAY TRANSFER PAY.BONUS_EARN_CODE;
ALTER SCHEMA TRNPAY TRANSFER PAY.CTRL_ALL_PAY_RUNS_20132016;
ALTER SCHEMA TRNPAY TRANSFER PAY.LK_ACTION_REASON_CODE_TBL;
ALTER SCHEMA TRNPAY TRANSFER PAY.LK_BUS_UNIT;
ALTER SCHEMA TRNPAY TRANSFER PAY.LK_COMPANY_TBL;
ALTER SCHEMA TRNPAY TRANSFER PAY.LK_EARNCODE_TBL;
ALTER SCHEMA TRNPAY TRANSFER PAY.LK_EMPL_TYPE_TBL;
ALTER SCHEMA TRNPAY TRANSFER PAY.LK_PAY_RUN_ID;
ALTER SCHEMA TRNPAY TRANSFER PAY.LK_PAY_TAX__TAX_CLASS_TBL;
ALTER SCHEMA TRNPAY TRANSFER PAY.LK_PAYCHECK_OPTION;
ALTER SCHEMA TRNPAY TRANSFER PAY.LK_PAYROLL_STATUS;
ALTER SCHEMA TRNPAY TRANSFER PAY.OC_CHECKS_DATES_REASONS_20131026;
ALTER SCHEMA TRNPAY TRANSFER PAY.TAX_DIST_MULTISTATE;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_PAYCHECK_EARNS_DETAIL_20132014;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_PAYCHECK_EARNS_DETAIL_20152016;
ALTER SCHEMA TRNPAY TRANSFER PAY.LK_PAYGROUP_TBL;
ALTER SCHEMA TRNPAY TRANSFER PAY.LK_PAYGROUP_FREQ_DESCR;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_PAYCHECK_TAX_ALL;
ALTER SCHEMA TRNPAY TRANSFER PAY.BASE_W2_ALL;