--Table consolidation from two component tables

SELECT *

INTO [IAACE1].[TRNPAY].[BASE_PAYCHECK_EARNS_DETAIL_ALL]

FROM
	(
	SELECT * FROM [IAACE1].[TRNPAY].[BASE_PAYCHECK_EARNS_DETAIL_20132014]
	UNION 
	SELECT * FROM [IAACE1].[TRNPAY].[BASE_PAYCHECK_EARNS_DETAIL_20152016]
	) a